### ISSUE TITLE
Start convo with chuck about data

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/library_data_services_model#21]

**Comment by npie762** [comment]
Notes from Nathan's conversation with Chuck Jones about digital imaging in archaeology, Sept. 29, 2016:

-Mostly scanning of artifacts (3d scripts etc), with lasers and similar instruments (RTI) to detect nuances not otherwise visible such as tool marks and/or scripts that have been written over multiple times. 
Also use of drones to detect shards and other indications of artifacts not easily captured from the ground
Also virtual unrolling of rolled scripts for which unrolling would be destructive

-Images can also be used for reconstruction in the event of destructive sampling or retrieval of artifacts
Also a growing desire to present/publish visualizations of the data digitally and via the web as time-series

-More and more field archaeological data are captured digitally, but the discipline isn't far from using paper so data management challenges are many

-However, there are some some examples of archaeological projects doing a good job of digital data management and preservation including one [based at Stanford or Berkeley?] that's using the California Digital Library back-end for digital preservation

-Finally, some movement towards other related efforts like Archeo-gaming?

-Other loosely related projects:
Pleiades: https://pleiades.stoa.org/
Pelagios: http://pelagios.org/maps/greco-roman/
